### ISSUE TITLE
Request: Save ngine editor settings per project, use template saved with editor

### ISSUE THREAD

**Issue by RaphaelTetreault** [stefanmielke/ngine#1]
I think it would be convenient and more flexible if the ngine.engine.json editor settings file was saved on a per-project basis (in the .ngine folder). The file generated could be created from a, or selected from multiple, template files stored in the current directory (beside the ngine executable). This way, the user could define a template for the settings used to generate the settings file when a project is created. This allows each individual project to override those settings should the project benefit from this. The user could potentially have a button to save the current project's setting as a/the default template from within a project.

The one stumbling block I came across was when I updated ngine, since I didn't know the settings were in the executable's folder, resulting in having to manually reset my settings. This would also help mitigate this issue, as a project could be opened and the settings copied over to the new executable's location.

**Comment by stefanmielke** [comment]
I can use another location (like %AppData% on WIndows, for example). That way it wouldn't cause the issue of overwriting settings when updating. Would that solve your issue?

Not sure if you have another use case to have project specific settings (although I do see _some_ value on having the emulator being different per project, but then I can think of other ways to do that).

**Comment by RaphaelTetreault** [comment]
%AppData% (or similar) would likely suffice. I know I won't be using many different emulators or versions of emulators any time soon. Perhaps the Engine settings could be the default for the emulator path, and the user could specify another emulator to use in  the Project settings tab?

In any case, I think the main thing for me is that some settings can persist across versions of ngine and that duplicate work setting up paths / variables can be mitigated.

**Comment by stefanmielke** [comment]
Ok, makes sense to me (using AppData on Windows and similar on Linux).

When upgrading, you can just drop the files on top of the current install. It'll likely only need to replace the exe anyway (all the other files are DLL deps that shouldn't change anytime soon).

**Comment by stefanmielke** [comment]
https://github.com/stefanmielke/ngine/commit/cf3fea70314e67a6cfa6ef0e2b4be2c2c6e96202 should close this issue. Let me know if you can test the build to confirm @RaphaelTetreault.

It should save like this (and migrate the current file into that folder the first time you run, if you already have it):
    - Windows: %AppData%/ngine/
    - Linux: ~/.ngine/

Thanks!

**Comment by RaphaelTetreault** [comment]
Working for me on Windows 10!

Perhaps worth noting: it is saved to" `<user>\AppData\Roaming\ngine\`
