### ISSUE TITLE
Remove all generated files when removing script

### ISSUE THREAD

**Issue by RaphaelTetreault** [stefanmielke/ngine#2]
When removing a script using the in-editor prompt, only the `.c` and `.h` files are removed from the `scripts/` folder, leaving behind `.d` and `.o` files from the build process.

I'm not sure if there is a reason to leave them behind. If not, it would be nice for those to be deleted, too.

**Comment by stefanmielke** [comment]
I will be adding this soon. In the meantime you can use 'Tasks->Clean/Build' to remove them.
